created CRUD and middlewares
Lambda-School-Labs/Labs25-Bridges_to_Prosperity-TeamA-be pull request #6
Opened 2020-08-12 22:13 UTC by anthonyamaro15

# Description

created CRUD operations and added middlewares to validate ID's and input values, added routes.

Fixes #3 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## Change Status

- [ ] Complete, tested, ready to review and merge
- [x] Complete, but not tested (may need new tests)
- [ ] Incomplete/work-in-progress, PR is for discussion/feedback

## Has This Been Tested

- [x] Yes
- [ ] No
- [ ] Not necessary

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] My code has been reviewed by at least one peer
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] There are no merge conflicts

2020-08-13 21:29 UTC, jameslcarpino reviewed
code looks good & clean. 

I'm seeing some errors on bridgeRouter.js, not sure if they are from an older push.

2020-08-13 23:00 UTC, JimmyMcBride requested changes
The test coverage is failing. If you get that working and set this pr from draft to ready for review, I'll get it merged for you guys. :fire:

2020-08-17 16:00 UTC, JimmyMcBride approved these changes

2020-08-17 16:01 UTC, JimmyMcBride approved these changes
Looks good! Thanks for making those changes!

2020-08-17 16:01 UTC, merged